In [2]:
import pickle
import pandas as pd
from sklearn.linear_model import LogisticRegression
import numpy as np
with open ('/Users/jennifer/Desktop/Phan_Metis/Project 3/Pickle Data/df_all_downsamp.pkl','rb') as picklefile:
    df_all_down_train = pickle.load(picklefile)
y_D = df_all_down_train[['certified']]

X_D = df_all_down_train[df_all_down_train.columns[0:-1]]
X_D = X_D[X_D.columns[:12]]

log_model = LogisticRegression(class_weight='balanced',C=.1,penalty='l1')

log_model.fit(X_D,np.ravel(y_D))

LogisticRegression(C=0.1, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l1', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [31]:
with open ('/Users/jennifer/Desktop/Phan_Metis/Project 3/Pickle Data/df_all_downsamp.pkl','rb') as picklefile:
    df_all_test= pickle.load(picklefile)

In [169]:
y_T = df_all_test[['certified']]

X_T = df_all_test[df_all_test.columns[0:-1]]
X_T = X_T[X_T.columns[:12]]

In [170]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
y_pred = log_model.predict(X_T)
acc_score = accuracy_score(y_T, y_pred)
prec_score = precision_score(y_T, y_pred)
rec_score = recall_score(y_T, y_pred)
f1 = f1_score(y_T, y_pred)

In [80]:
y_pred

array([0, 1, 1, ..., 1, 1, 0], dtype=uint8)

0.78791893667988044

In [37]:
print(acc_score)
print(prec_score)
print(rec_score)
print(f1)

0.78791893668
0.734051352749
0.902995357514
0.809805804017


In [51]:
#Function will plot confusion matrix plot
import matplotlib.pyplot as plt
def plot_confusion_matrix(cm,title='Confusion matrix',cmap=plt.cm.Reds):
    plt.imshow(cm,interpolation='nearest',cmap=cmap)
    plt.title(title)
    plt.colorbar()
    plt.tight_layout()
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')

In [60]:
# Create train_score that will return precision and recall and plot confusion matrix
from sklearn.cross_validation import cross_val_score,train_test_split
from sklearn.metrics import confusion_matrix
from sklearn import cross_validation
def train_score(classifier,X,y):
    X_train,X_test,y_train,y_test = cross_validation.train_test_split(X,y, test_size =.2)
    y_train=np.ravel(y_train)
    clf = classifier.fit(X_train,y_train)
    ## accuracy for test and train set
    train_accuracy = clf.score(X_train,y_train)
    test_accuracy = clf.score(X_test,y_test)
    
    print("Training Data Accuracy: %0.2f" %(train_accuracy))
    print("Test Data Accuracy:     %0.2f" %(test_accuracy))
    
    y_true = y_test
    y_pred = clf.predict(X_test)
    conf = confusion_matrix(y_true, y_pred,labels=[1,0])
    print(conf)
    
    print ('\n')
    print ("Precision:              %0.2f" %(conf[0, 0] / (conf[0, 0] + conf[1, 0])))
    print ("Recall:                 %0.2f"% (conf[0, 0] / (conf[0, 0] + conf[0, 1])))
    print ("Specificity:                 %0.2f"% (conf[1, 1] / (conf[1, 1] + conf[1, 0])))
    cm=confusion_matrix(y_true,y_pred,labels=[1,0])
    plt.figure()
    plot_confusion_matrix(cm)

In [61]:
train_score(log_model,X_T,y_T)

Training Data Accuracy: 0.79
Test Data Accuracy:     0.79
[[8557  967]
 [3019 6327]]


Precision:              0.74
Recall:                 0.90
Specificity:                 0.68


In [64]:
from sklearn.metrics import roc_curve, auc
y_score = log_model.predict_proba(X_T)[:,1]
fpr, tpr, _ = roc_curve(y_T,y_score)
roc_auc = auc(fpr,tpr)
roc_auc

0.86354108800616602

In [65]:
y_score

array([ 0.02329436,  0.57220141,  0.8004291 , ...,  0.99058014,
        0.63019945,  0.45020576])

In [77]:
X_T[1:2]

prevailing_wage  accept_rate_soc  total_apps_soc  accept_rate_emp  \
2328565          38251.0         0.932176          6163.0         0.960677   

         total_apps_emp  2011.0  2012.0  2013.0  2014.0  2015.0  2016.0  y  
2328565    14673.032817       0       1       0       0       0       0  1

In [332]:
df_all_down_train

prevailing_wage  accept_rate_soc  total_apps_soc  accept_rate_emp  \
2169920          40250.0         0.960218     2564.000000         0.571429   
2328565          38251.0         0.932176     6163.000000         0.960677   
1166762          85763.0         0.985462   494164.000000         0.990696   
2395346          55931.0         0.919539    15697.000000         0.500000   
1541743          56243.0         0.985462   494164.000000         0.960677   
2423098         220022.4         0.850537     4001.000000         0.968929   
1871747          47216.0         0.985462   494164.000000         0.500000   
1788253          47840.0         0.932176     6163.000000         0.500000   
2784817          59779.0         0.897059      476.000000         0.970874   
1976324          48630.0         0.990147   173553.000000         0.941176   
2634087          54662.4         0.797759     3837.000000         0.750000   
2594581          43035.2         0.969711     4457.000000         0.946429   
2123026          75150.0         0.983693   402278.000000         0.988901   
2359571          28850.0         0.860577      208.000000         0.700000   
1449343          60403.0         0.983693   402278.000000         0.993581   
2660677          33446.0         0.817073     1558.000000         0.333333   
2711562          45000.0         0.962940    32866.000000         0.960677   
2220701          52021.0         0.959184    51695.000000         0.960677   
524998          125592.0         0.975608    35175.000000         0.976636   
2730013          59425.6         0.980720    38952.000000         0.666667   
2136942          81661.0         0.971327    65044.000000         0.983247   
1188977         120224.0         0.985462   494164.000000         0.965854   
570441           70658.0         0.964927     4676.000000         0.500000   
156885           77147.0         0.985462   494164.000000         0.985085   
2266091          72488.0         0.906474    12018.000000         0.500000   
2830617         265655.0         0.850537     4001.000000         0.750000   
2730564          54662.4         0.797759     3837.000000         0.333333   
825135           60756.8         0.911022     7766.000000         0.500000   
2870451          62546.0         0.985462   494164.000000         0.971014   
2299139          38397.0         0.935785    36331.000000         0.666667   
...                  ...              ...             ...              ...   
829604           97178.0         0.978185    81182.000000         0.977842   
2017472          86736.0         0.983693   402278.000000         0.960677   
914486           73258.0         0.983693   402278.000000         0.945652   
2249907          98509.0         0.983693   402278.000000         0.991994   
926279           64314.0         0.990147   173553.000000         0.992013   
118956           61797.0         0.985462   494164.000000         0.960677   
2681225         125000.0         0.942029     2967.000000         0.857143   
901192           75629.0         0.966983    26683.000000         0.857143   
679503          108805.0         0.983693   402278.000000         0.952381   
1170522          81266.0         0.985462   494164.000000         0.986163   
789732           27081.6         0.831325       83.000000         0.857143   
2344692          56930.0         0.983179   386776.000000         0.980392   
755146           76918.0         0.990147   173553.000000         0.998034   
1659158         108700.0         0.983693   402278.000000         0.988077   
2793006          68661.0         0.954020    32362.000000         0.991366   
1298257          67350.0         0.990147   173553.000000         0.995726   
1324589          98675.0         0.983693   402278.000000         0.997170   
2265537          85530.0         0.983693   402278.000000         0.937500   
2658099          88317.0         0.964043    11931.000000         0.998408   
1874602          58760.0       

In [ ]:
with open ('/Users/jennifer/Desktop/Phan_Metis/Project 3/Pickle Data/df_all_downsamp.pkl','rb') as picklefile:
    df_all_down_train = pickle.load(picklefile)
y_D = df_all_down_train[['certified']]
# X
X_D = df_all_down_train[df_all_down_train.columns[0:12]]

 

In [215]:
X_D

prevailing_wage  accept_rate_soc  total_apps_soc  accept_rate_emp  \
2169920          40250.0         0.960218     2564.000000         0.571429   
2328565          38251.0         0.932176     6163.000000         0.960677   
1166762          85763.0         0.985462   494164.000000         0.990696   
2395346          55931.0         0.919539    15697.000000         0.500000   
1541743          56243.0         0.985462   494164.000000         0.960677   
2423098         220022.4         0.850537     4001.000000         0.968929   
1871747          47216.0         0.985462   494164.000000         0.500000   
1788253          47840.0         0.932176     6163.000000         0.500000   
2784817          59779.0         0.897059      476.000000         0.970874   
1976324          48630.0         0.990147   173553.000000         0.941176   
2634087          54662.4         0.797759     3837.000000         0.750000   
2594581          43035.2         0.969711     4457.000000         0.946429   
2123026          75150.0         0.983693   402278.000000         0.988901   
2359571          28850.0         0.860577      208.000000         0.700000   
1449343          60403.0         0.983693   402278.000000         0.993581   
2660677          33446.0         0.817073     1558.000000         0.333333   
2711562          45000.0         0.962940    32866.000000         0.960677   
2220701          52021.0         0.959184    51695.000000         0.960677   
524998          125592.0         0.975608    35175.000000         0.976636   
2730013          59425.6         0.980720    38952.000000         0.666667   
2136942          81661.0         0.971327    65044.000000         0.983247   
1188977         120224.0         0.985462   494164.000000         0.965854   
570441           70658.0         0.964927     4676.000000         0.500000   
156885           77147.0         0.985462   494164.000000         0.985085   
2266091          72488.0         0.906474    12018.000000         0.500000   
2830617         265655.0         0.850537     4001.000000         0.750000   
2730564          54662.4         0.797759     3837.000000         0.333333   
825135           60756.8         0.911022     7766.000000         0.500000   
2870451          62546.0         0.985462   494164.000000         0.971014   
2299139          38397.0         0.935785    36331.000000         0.666667   
...                  ...              ...             ...              ...   
829604           97178.0         0.978185    81182.000000         0.977842   
2017472          86736.0         0.983693   402278.000000         0.960677   
914486           73258.0         0.983693   402278.000000         0.945652   
2249907          98509.0         0.983693   402278.000000         0.991994   
926279           64314.0         0.990147   173553.000000         0.992013   
118956           61797.0         0.985462   494164.000000         0.960677   
2681225         125000.0         0.942029     2967.000000         0.857143   
901192           75629.0         0.966983    26683.000000         0.857143   
679503          108805.0         0.983693   402278.000000         0.952381   
1170522          81266.0         0.985462   494164.000000         0.986163   
789732           27081.6         0.831325       83.000000         0.857143   
2344692          56930.0         0.983179   386776.000000         0.980392   
755146           76918.0         0.990147   173553.000000         0.998034   
1659158         108700.0         0.983693   402278.000000         0.988077   
2793006          68661.0         0.954020    32362.000000         0.991366   
1298257          67350.0         0.990147   173553.000000         0.995726   
1324589          98675.0         0.983693   402278.000000         0.997170   
2265537          85530.0         0.983693   402278.000000         0.937500   
2658099          88317.0         0.964043    11931.000000         0.998408   
1874602          58760.0       

In [328]:
   

# log_model = LogisticRegression(class_weight='balanced',C=.1,penalty='l1')
log_model = LogisticRegression(class_weight='balanced',C=.1,penalty='l1')
log_model.fit(X_D,np.ravel(y_D))

LogisticRegression(C=0.1, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l1', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [329]:
y_pred = log_model.predict(X_T)
acc_score = accuracy_score(y_T, y_pred)
prec_score = precision_score(y_T, y_pred)
rec_score = recall_score(y_T, y_pred)
f1 = f1_score(y_T, y_pred)

In [218]:
y_pred

array([0, 1, 1, ..., 1, 0, 0], dtype=uint8)

In [212]:
y_T

certified
2169920          0
2328565          0
1166762          0
2395346          0
1541743          0
2423098          0
1871747          0
1788253          0
2784817          0
1976324          0
2634087          0
2594581          0
2123026          0
2359571          0
1449343          0
2660677          0
2711562          0
2220701          0
524998           0
2730013          0
2136942          0
1188977          0
570441           0
156885           0
2266091          0
2830617          0
2730564          0
825135           0
2870451          0
2299139          0
...            ...
829604           1
2017472          1
914486           1
2249907          1
926279           1
118956           1
2681225          1
901192           1
679503           1
1170522          1
789732           1
2344692          1
755146           1
1659158          1
2793006          1
1298257          1
1324589          1
2265537          1
2658099          1
1874602          1
948700           1
435625           1
2303042          1
2870879          1
303876           1
286126           1
586305           1
452336           1
1970833          1
2664668          1

[94346 rows x 1 columns]

In [333]:
print(acc_score)
print(prec_score)
print(rec_score)
print(f1)

0.788205117334
0.734207307619
0.903482924554
0.810096747828


In [334]:
train_score(log_model,X_T,y_T)

Training Data Accuracy: 0.79
Test Data Accuracy:     0.78
[[8552  896]
 [3191 6231]]


Precision:              0.73
Recall:                 0.91
Specificity:                 0.66


In [300]:
mc_model = log_model

In [339]:


def certified_or_denied(prevailing_wage_float,
                            accept_rate_soc_float,
                            total_apps_soc_int,
                            accept_rate_emp_float,
                            total_apps_emp_int,
                            yr_2011_int,
                            yr_2012_int,
                            yr_2013_int,
                            yr_2014_int,
                            yr_2015_int,
                            yr_2016_int,
                            full_time_int,
                        mc_model=log_model):
    
    input_df = pd.DataFrame({'Prevailing Wage': prevailing_wage_float,
                             'Certified Rate by SOC':accept_rate_soc_float,
                            'Total Petitions by SOC':total_apps_soc_int,
                            'Certified Rate by Employer':accept_rate_emp_float,
                            'Total Petitions by Employer': total_apps_emp_int,
                            'Petition submitted in 2011': yr_2011_int,
                            'Petition submitted in 2012': yr_2012_int,
                            'Petition submitted in 2013': yr_2013_int,
                            'Petition submitted in 2014': yr_2014_int,
                            'Petition submitted in 2015': yr_2015_int,
                            'Petition submitted in 2016': yr_2016_int,
                            'Full Time Position': full_time_int}, index=[0])
                 

    prediction = mc_model.predict(input_df)[0]
    predict_pct1 = str(mc_model.predict_proba(input_df)[0][1])
#     print(prediction)
#     print(mc_model.predict_proba(input_df))
  
    
#     print(prediction)
#     print(predict_pct1)

#     message_array = ["You're H-1B Petition will be Denied!","You're H-1B Petition will be Certified!"]

    message = ['The petition will likely be denied!','The petition will likely be certified!']

    return message[prediction]

In [359]:

certified_or_denied(10,.50,10,.98,0,1,1,0,0,0,0,0,mc_model=log_model)

'The petition will likely be certified!'